In [5]:
!pip install tensorflow

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
X=np.random.randn(100,1)
Y=X*5

In [14]:
def start_traning(weight):
  print(f"Creating A Network with this weight :{weight}")
  model=tf.keras.Sequential()
  model.add(tf.keras.Input(shape=(1,)))
  init=tf.keras.initializers.Constant(weight)

  for i in range(10):
    model.add(tf.keras.layers.Dense(1,activation='relu',kernel_initializer=init))

  with tf.GradientTape() as tape:
    prediction=model(X)
    # ✅ RIGHT: Build it (), then use it (Y, prediction)
    loss = tf.keras.losses.MeanSquaredError()(Y, prediction)

  grads=tape.gradient(loss,model.trainable_variables)
  for g in grads:
      print(g)


In [ ]:
start_traning(0.1)

Creating A Network with this weight :0.1
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-2.2000005e-08], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-2.2000003e-07], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-2.2000004e-06], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-2.2000002e-05], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400002e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-0.00022], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400002e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-0.0022], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400002e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-0.022], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-0.22], shape=(1,), dtype=float32)
tf.Tensor([[-1.5400003e-07]], shape=(1, 1), dtype=float32)
tf.Tensor([-2.2], 